repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.20.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.13.0"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
      - id: ruff-format
